apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: flask-ci-pipeline
  namespace: kg7460502-dev
spec:
  params:
    - name: IMAGE_NAME
      type: string
    - name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string

  workspaces:
    - name: workspace

  tasks:
    # 1) git-clone
    - name: fetch-repository
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REVISION)
        - name: SUBDIRECTORY
          value: ""
        - name: DELETE_EXISTING
          value: "true"
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: workspace

    # 2) flake8 + nose2 (tests-task)
    - name: tests
      runAfter:
        - fetch-repository
      taskRef:
        name: tests-task
      workspaces:
        - name: source
          workspace: workspace

    # 3) buildah
    - name: build
      runAfter:
        - tests
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLS_VERIFY
          value: "false"
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: workspace

    # 4) deploy (openshift-client)
    - name: deploy
      runAfter:
        - build
      params:
        - name: SCRIPT
          value: |
            oc new-app --docker-image $(params.IMAGE_NAME)
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: namespace
            value: openshift-pipelines

  finally:
    # 5) cleanup
    - name: cleanup
      taskRef:
        name: cleanup-task
